import { useEffect, useState } from "react";
import { api } from "../api/client";
import type { Action, Analysis, Report } from "../types/api";
import type { Page } from "../layout/Shell";
import { Empty, ErrorState, Loading } from "../ui/State";

const pairs=(value:unknown):Record<string,unknown>=>Array.isArray(value)?Object.fromEntries(value.filter(Array.isArray).map(item=>[String(item[0]),item[1]])):value&&typeof value==="object"?value as Record<string,unknown>:{};
function useReport(scanId:string|null,userId:string|null){const[data,setData]=useState<Report>();const[error,setError]=useState("");const load=async()=>{if(!scanId||!userId)return;try{setError("");setData(await api.report(scanId,userId))}catch(cause){setError(cause instanceof Error?cause.message:"We couldn't load this observation.")}};useEffect(()=>{void load()},[scanId,userId]);return{data,error,load}}

export function ExplanationPage({scanId,userId,setPage}:{scanId:string|null;userId:string|null;setPage?:((p:Page)=>void)}){
  const{data,error,load}=useReport(scanId,userId);
  if(error)return <ErrorState message={error} retry={load}/>;
  if(!scanId)return <Empty><p>Select an observation to view its available context.</p></Empty>;
  if(!data)return <Loading>Loading source-grounded context…</Loading>;
  const evidence=data.sections.find(item=>item.title==="Evidence & Explanation");
  const explanation=evidence?.items.find(item=>item.label==="Evidence-grounded explanation")?.value;
  const sources=evidence?.items.filter(item=>item.label==="External evidence").map(item=>pairs(item.value))??[];
  return <section className="page detail-page">{setPage&&<button className="back-link" onClick={()=>setPage("result")}>← Back to your observation</button>}<p className="eyebrow">Context</p><h1>Why was this flagged?</h1>{!explanation&&!sources.length?<Empty><p>Source-grounded context isn't available for this observation yet.</p></Empty>:<section className="report-section"><p className="lede">This {explanation?"explanation provides":"source material provides"} available context for a model-derived observation. It is not a medical diagnosis.</p>{explanation?<p>{String(explanation)}</p>:<p className="muted">Source-grounded context is available. A generated explanation is not configured.</p>}<div className="source-cards">{sources.map((source,index)=><article className="report-item" key={index}><p className="eyebrow">Source</p><h2>{String(source.title||"Source details")}</h2>{Boolean(source.organization)&&<p>{String(source.organization)}</p>}{typeof source.url==="string"&&<a href={source.url} target="_blank" rel="noreferrer">View source →</a>}</article>)}</div></section>}</section>
}

export function NextPage({analysis,setPage}:{analysis:Analysis|null;setPage:(p:Page)=>void}){const referral=analysis?.safety?.professional_assessment_recommended===true;return <section className="page detail-page"><button className="back-link" onClick={()=>setPage("result")}>← Back to your observation</button><p className="eyebrow">What you can do next</p><h1>{referral?"Consider professional assessment.":"Continue monitoring."}</h1><p className="lede">This next step reflects the available result and does not provide a diagnosis.</p>{referral?<section className="result-panel"><p>Choose a location only when you are ready to find nearby dermatology provider options.</p><button className="button" onClick={()=>setPage("products")}>Find a dermatologist →</button></section>:<section className="result-panel"><p>Take another observation later under similar lighting and framing to continue building your personal record.</p><button className="button" onClick={()=>setPage("scan")}>Start another observation →</button></section>}</section>}

export function ProductsPage({scanId,userId,analysis}:{scanId:string|null;userId:string|null;analysis:Analysis|null}){const[data,setData]=useState<Action>();const[error,setError]=useState("");const[manual,setManual]=useState(false);const[city,setCity]=useState("");const[busy,setBusy]=useState(false);const professional=analysis?.safety?.professional_assessment_recommended===true;const loadProducts=async()=>{if(!scanId||!userId)return;try{setError("");setData(await api.products(scanId,userId))}catch(cause){setError(cause instanceof Error?cause.message:"We couldn't load available skincare categories.")}};useEffect(()=>{if(!professional)void loadProducts()},[scanId,userId,professional]);const find=async(location:Record<string,unknown>)=>{if(!scanId||!userId)return;setBusy(true);try{setError("");setData(await api.referrals(scanId,userId,location))}catch(cause){setError(cause instanceof Error?cause.message:"We couldn't load provider options right now.")}finally{setBusy(false)}};const geo=()=>navigator.geolocation?.getCurrentPosition(position=>void find({latitude:position.coords.latitude,longitude:position.coords.longitude}),()=>setManual(true));if(error)return <ErrorState message={error} retry={professional?()=>find(city?{city}:{}):loadProducts}/>;return <section className="page detail-page"><p className="eyebrow">{professional?"Referral options":"General skincare"}</p><h1>{professional?"Find dermatology providers near you":"General skincare categories"}</h1>{professional?<><p className="lede">Your location is used only for this provider search.</p>{!data&&<div className="actions"><button className="button" onClick={geo}>Use my location</button><button className="button secondary" onClick={()=>setManual(true)}>Enter location manually</button></div>}{manual&&!data&&<form className="manual-location" onSubmit={event=>{event.preventDefault();void find({city})}}><label>City<input value={city} onChange={event=>setCity(event.target.value)} required /></label><button className="button">Find providers</button></form>}{busy&&<Loading>Finding dermatology providers…</Loading>}{data&&<ActionItems items={data.items} providers empty="No dermatology providers were returned for this location."/>}</>:<>{data?<ActionItems items={data.items} empty="No general skincare categories are available for this observation."/>:<Loading>Checking available skincare categories…</Loading>}<p className="safe-note">These are general, brand-neutral categories supplied by the backend, not prescriptions or treatment guarantees.</p></>}</section>}
function ActionItems({items,empty,providers=false}:{items:Record<string,unknown>[];empty:string;providers?:boolean}){const allowed=providers?["name","address","distance_km","opening_hours","phone","website"]:["category_name","neutral_description"];return items.length?<div className="item-grid">{items.map((item,index)=><article className="item-card" key={index}>{allowed.filter(name=>item[name]!==undefined).map(name=><p key={name}><b>{name.replaceAll("_"," ")}</b><span>{String(item[name])}</span></p>)}</article>)}</div>:<Empty><p>{empty}</p></Empty>}
export function SettingsPage(){return <section className="page detail-page"><p className="eyebrow">Privacy</p><h1>Your observation, your control.</h1><p className="lede">SpectraDerm uses a pseudonymous observation record. Location is requested only if you choose to look for provider options.</p><p className="safe-note">Selected images are stored as private managed artifacts. Your browser filename is not used as a server-side reference.</p></section>}
